## all relative paths in this file has pybullet_planning as the root dir

## debug related
seed: None
verbose: true

## data collection mode
#parallel: true
#n_data: 3
parallel: false
n_data: 1


## pybullet related
sim:
  viewer: true
  lock: true
  simulate: false
  drive: true
  time_step: 0.05
  camera: true
  segment: false
  monitoring: false
  skip_prompt: false


robot:
  robot_name: 'feg'
  builder_name: 'build_robot_from_args'
  builder_kwargs:
    ## x, y, z joint limits for base motion planning
    custom_limits: [[0, -4, -0.5], [3, 8, 3]]
    initial_q: [2, 3, 0.7, 0, -1.57, 0]


world:
  ## method 1: use pre-specified builder inside world_builder/builders,
  ##         followed by builder specific arguments
  builder_name: 'test_kitchen_full'
  builder_kwargs:
    movable_categories: ['edible']
    goal_predicates: ['holding', 'on', 'in']
    verbose: false


data:
  out_dir: '../outputs/test_feg_kitchen_full/'
  save_failed_plans: true
  save_log: true
  save_commands: true
  ## by default images are generated afterward in batch by test_image_generation.py
  images:
    save_rgb: true
    save_depth: false
  resolution: [1280, 720]
  fx: 800
  ## {name: pose} pairs
  cameras:
    ## pose format 1: (point, quaternion)
    front_1: [[6.84, 2.9, 1.3], [0.5, 0.5, -0.5, -0.5]]
    ## pose format 2: (camera_point, target_point)
    front_2: {'camera_point': [3, 4, 1.8], 'target_point': [0, 4, 1]}
    top: {'camera_point': [2, 4, 3], 'target_point': [0, 4, 1]}
    ## pose format 3: (object_name, delta_to_target)
    zoomin1: {'name': 'minifridge', 'd': [2, 0, 1]}


## configuration for PDDLStream
planner:
  visualize: false
  timeout: 300
  domain_pddl: 'pddl_domains/feg_domain.pddl'
  stream_pddl: 'pddl_domains/feg_stream.pddl'
  downward_time: 1
  diverse: true
  dataset: false


## planning stream related
streams:
  debug: false
  cfree: false
  teleport: false
  movable_collisions: true
  base_collisions: true
  top_grasp_tolerance: 0.8
  ir_max_attempts: 15
  use_all_grasps: false