import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid", {"axes.facecolor": ".9"})

groups = ['Image', 'Relation', 'Value']

models = [
    'baseline', 'img=feature', 'img=one-hot',
    'rel=all', 'rel=no_init','rel=one-hot',
    'val=no-value', 'val=no-pose', 'val=no-position',
]

df = pd.DataFrame({
    'Area': ['Image', 'Image', 'Image',
             'Relation', 'Relation', 'Relation',
             'Value', 'Value', 'Value'],
    'Rank': ['VPT', 'feature only', 'one-hot only',
    'all init', 'no init','one-hot',
    'no value', 'no pose', 'no position'],
    'Validation Accuracy': [
        0.916, ## baseline - done
        0.921, ## img=feature - done
        0.881, ## img=one-hot - done
        0.918, ## rel=all - done
        0.741, ## rel=no_init - 265
        0.846, ## rel=one-hot - 178
        0, ## val=no-value - 202
        0.89, ## val=no-pose - 257
        0 ## val=no-position - 197
    ],
    'Validation TPR': [
        0.931, ## baseline - done
        0.9261, ## img=feature - done
        0.8522, ## img=one-hot - done
        0.9113, ## rel=all - done
        0.8276, ## rel=no_init - 265
        0.7685, ## rel=one-hot - 178
        0, ## val=no-value - 202
        0.9113, ## val=no-pose - 257
        0 ## val=no-position - 197
    ],
    'Validation TNR': [
        0.9027, ## baseline - done
        0.9159, ## img=feature - done
        0.9071, ## img=one-hot - done
        0.9248, ## rel=all - done
        0.6637, ## rel=no_init - 265
        0.9159, ## rel=one-hot - 178
        0, ## val=no-value - 202
        0.8717, ## val=no-pose - 257
        0 ## val=no-position - 197
    ],
})
df = df.set_index(['Area', 'Rank'])

fig = plt.figure(figsize=(12, 4))
plt.title('Ablation studies on classification accuracy (All fake data)', fontsize=16, pad=35)
plt.axis('off')

colors = ['b', 'g', 'r'] ## , 'y'
colors = ['#3498db', '#2ecc71', '#e74c3c'] ## , '#f1c40f'

for i, l in enumerate(groups):
    if i == 0:
        sub1 = fig.add_subplot(131+i)
    else:
        sub1 = fig.add_subplot(131+i, sharey=sub1)

    df.loc[l].plot(kind='bar', ax=sub1, color=colors)
    sub1.set_xticklabels(sub1.get_xticklabels(), rotation=0)
    sub1.set_xlabel(l, fontsize=12)
    sub1.tick_params(axis='x', which='major', pad=10)
    sub1.get_legend().remove()

    ## remove the edge color auto generated by dataframe.plot
    for i in range(len(sub1.__dict__['containers'])):
        for j in range(len(sub1.__dict__['containers'][i].__dict__['patches'])):
            sub1.__dict__['containers'][i].__dict__['patches'][j].__dict__['_edgecolor'] = (1, 1, 1, 0)

    # import ipdb; ipdb.set_trace()

handles, labels = sub1.get_legend_handles_labels()
fig.legend(handles, labels, ncol=4, loc='upper center', bbox_to_anchor=(0.5, 0.9))
plt.tight_layout()
plt.show()
